# Generated by Django 5.1.5 on 2025-02-05 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('variant', 'Variant')], default='variant', max_length=20)),
                ('url', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='products.variant')),
            ],
        ),
    ]
