# Generated by Django 5.1.5 on 2025-02-05 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('retailers', '0002_remove_retailer_address_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('gstin', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp_number', models.BigIntegerField()),
                ('alternative_contact_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='address.address')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierRetailerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_mappings', to='retailers.retailer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_mappings', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier-Retailer Mapping',
                'verbose_name_plural': 'Supplier-Retailer Mappings',
                'unique_together': {('supplier', 'retailer')},
            },
        ),
    ]
