# Generated by Django 5.1.5 on 2025-02-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('gstin', models.CharField(max_length=100)),
                ('whatsapp_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('alternative_contact_number', models.CharField(max_length=100)),
                ('address_id', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
