# Generated by Django 5.1.5 on 2025-02-05 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('retailers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='retailer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailers', to='address.address'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='alternative_contact_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='gstin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='owner_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='whatsapp_number',
            field=models.BigIntegerField(),
        ),
    ]
